name: CMake on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add GCC PPA and Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt list -a gcc-14 g++-14 || echo "gcc-14 or g++-14 not found in PPA"

    - name: Install GCC from Source
      if: failure() # Only run if previous step failed
      run: |
        sudo apt update
        sudo apt install -y wget build-essential
        wget https://ftp.gnu.org/gnu/gcc/gcc-14.0.0/gcc-14.0.0.tar.gz
        tar -xzf gcc-14.0.0.tar.gz
        cd gcc-14.0.0
        ./contrib/download_prerequisites
        mkdir build
        cd build
        ../configure --enable-languages=c,c++ --disable-multilib
        make -j$(nproc)
        sudo make install

    - name: Set GCC 14 Environment Variables
      run: |
        export CC=/usr/local/bin/gcc
        export CXX=/usr/local/bin/g++
        echo "CC=${CC}" >> $GITHUB_ENV
        echo "CXX=${CXX}" >> $GITHUB_ENV

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_C_COMPILER=${{ env.CC }} -DCMAKE_CXX_COMPILER=${{ env.CXX }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ env.BUILD_TYPE }}
